---
- name: Create a new swarm cluster with default parameters
  docker_swarm:
    advertise_addr: "{{ hostvars.manager.ansible_all_ipv4_addresses | ipaddr(hostvars.manager.swarm_cluster_network + '/24') | first }}"
    state: present
  run_once: yes
  register: swarm_info

- name: Configure to run manager node as manager-only
  docker_node:
    hostname: "{{ inventory_hostname }}"
    availability: drain
