---
- name: Copy the NGINX repository definition
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: Install nginx
  package:
    name: nginx
    state: present

- name: Overwrite nginx.conf file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Reload nginx

- name: Add nginx confing file
  template:
    src: manager.conf.j2
    dest: /etc/nginx/conf.d/manager.conf
  notify:
    - Reload nginx

- name: Add firewalld rule for http service
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: Add firewalld rule for https service
  firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled

- block:
    - name: Toggle SELinux boolean for connecting database
      seboolean:
        name: httpd_can_network_connect_db
        state: yes
        persistent: yes
  when:
    - ansible_os_family == 'RedHat'

- name: Manage nginx service state
  systemd:
    name: nginx
    state: started
    daemon_reload: yes
    enabled: yes
