---
- name: Copy the NGINX repository definition
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: Install nginx
  dnf:
    name:
      - nginx
    state: present

- name: Overwrite nginx.conf file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Reload nginx

- name: Add nginx confing file
  template:
    src: loadbalancer.conf.j2
    dest: /etc/nginx/conf.d/loadbalancer.conf
  notify:
    - Reload nginx

- name: Add firewalld rule for http service
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: Add firewalld rule for https service
  firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled

- name: Toggle SELinux boolean for connecting upstreams
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Manage nginx service state
  systemd:
    name: nginx
    state: started
    daemon_reload: yes
    enabled: yes
