version: "3.7"

services:
  webapp:
    image: manager:5000/webapp:latest
    ports:
      - 11080:80
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      labels:
        com.docker.lb.hosts: manager
        com.docker.lb.port: 11080
        com.docker.lb.sticky_session_cookie: session
