---
  - name: Join as worker to docker-swarm
    docker_swarm:
      state: join
      advertise_addr: "{{ ansible_default_ipv4.address }}"
      join_token: "{{ hostvars.manager.swarm_info.swarm_facts.JoinTokens.Worker }}"
      remote_addrs:
        - "{{ hostvars.manager.ansible_default_ipv4.address }}"
